/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mmorpg_assignment;

import java.awt.Component;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import static java.lang.Integer.parseInt;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JOptionPane;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author gover_000
 */
public class UserManagement extends javax.swing.JFrame {

    public String usernameLogIn = "";
    public Integer balanceCurrent = 0;
    public Integer slotsCurrent = 0;
    public Integer monthsCurrent = 0;
    /**
     * Creates new form NewJFrame
     */
    public UserManagement(String username) {
        usernameLogIn = username;
        initComponents();
        
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("MMORPG_assignmentPU");
        EntityManager em = emf.createEntityManager();
        em.getTransaction().begin();
        
        Users checkUser = em.find(Users.class, usernameLogIn);
        balanceCurrent = checkUser.getBalance();
        MoneyAmountTxtfield1.setText(balanceCurrent.toString()); 
        slotsCurrent = checkUser.getCharacterSlots();
        SlotsTxtfield1.setText(slotsCurrent.toString());
        monthsCurrent = checkUser.getMonthsPayed();
        SubscriptionAmountTxtfield.setText(monthsCurrent.toString());
        
        em.getTransaction().commit();
        em.close();
        emf.close();
        
        MoneyAmountTxtfield.addFocusListener(new FocusListener() {
            public void focusGained(FocusEvent e) { 
                 MoneyAmountTxtfield.setText("");
            }
             public void focusLost(FocusEvent e) { 
                 //
            }
        });
                
        SlotsTxtfield.addFocusListener(new FocusListener() {
            public void focusGained(FocusEvent e) { 
                 SlotsTxtfield.setText("");
            }
             public void focusLost(FocusEvent e) { 
                 //
            }
        });
    }
    
    public UserManagement() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Backbutton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        MoneyAmountTxtfield = new javax.swing.JTextField();
        MoneyTransaction = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        OneMonthButton = new javax.swing.JRadioButton();
        twoMonthsButton = new javax.swing.JRadioButton();
        threeMonthsButton = new javax.swing.JRadioButton();
        YearButton = new javax.swing.JRadioButton();
        RenovateButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        SlotsTxtfield = new javax.swing.JTextField();
        SlotsButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        MoneyAmountTxtfield1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        SlotsTxtfield1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        SubscriptionAmountTxtfield = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(775, 450));
        setResizable(false);

        jPanel1.setPreferredSize(new java.awt.Dimension(775, 400));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("User Management");

        Backbutton.setText("Back");
        Backbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackbuttonActionPerformed(evt);
            }
        });

        jLabel2.setText("Add money: ");

        MoneyAmountTxtfield.setText("Amount");
        MoneyAmountTxtfield.setToolTipText("");
        MoneyAmountTxtfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MoneyAmountTxtfieldActionPerformed(evt);
            }
        });

        MoneyTransaction.setText("Complete transaction");
        MoneyTransaction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MoneyTransactionActionPerformed(evt);
            }
        });

        jLabel3.setText("Renew Subscription:");

        buttonGroup1.add(OneMonthButton);
        OneMonthButton.setText("1 month (5)");

        buttonGroup1.add(twoMonthsButton);
        twoMonthsButton.setText("2 months (8)");

        buttonGroup1.add(threeMonthsButton);
        threeMonthsButton.setText("3 months (10)");
        threeMonthsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threeMonthsButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(YearButton);
        YearButton.setText("1 year (35)");

        RenovateButton.setText("Renovate");
        RenovateButton.setActionCommand("");
        RenovateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RenovateButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("Buy character slots:");

        SlotsTxtfield.setText("Amount");

        SlotsButton.setText("Buy slot(s)");
        SlotsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SlotsButtonActionPerformed(evt);
            }
        });

        jLabel5.setText("Current balance:");

        MoneyAmountTxtfield1.setEditable(false);
        MoneyAmountTxtfield1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MoneyAmountTxtfield1ActionPerformed(evt);
            }
        });

        jLabel6.setText("Current amount of slots:");

        SlotsTxtfield1.setEditable(false);

        jLabel7.setText("Months Left:");

        SubscriptionAmountTxtfield.setEditable(false);
        SubscriptionAmountTxtfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubscriptionAmountTxtfieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Backbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(25, 25, 25))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(MoneyAmountTxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(MoneyAmountTxtfield1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(MoneyTransaction, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(OneMonthButton)
                                    .addComponent(jLabel3)
                                    .addComponent(twoMonthsButton)
                                    .addComponent(threeMonthsButton)
                                    .addComponent(YearButton)
                                    .addComponent(RenovateButton)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SubscriptionAmountTxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(65, 65, 65)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(SlotsTxtfield1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(32, 32, 32)
                                .addComponent(SlotsTxtfield))
                            .addComponent(SlotsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(269, 269, 269)
                        .addComponent(jLabel1)))
                .addGap(0, 55, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(MoneyAmountTxtfield1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7)
                                .addComponent(SubscriptionAmountTxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(OneMonthButton))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(MoneyAmountTxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(MoneyTransaction))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SlotsTxtfield1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(SlotsTxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SlotsButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(twoMonthsButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(threeMonthsButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(YearButton)
                .addGap(18, 18, 18)
                .addComponent(RenovateButton)
                .addGap(19, 19, 19)
                .addComponent(Backbutton)
                .addGap(36, 36, 36))
        );

        jTabbedPane1.addTab("User Managment", jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 756, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Character Management", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 761, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        jTabbedPane1.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void threeMonthsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threeMonthsButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_threeMonthsButtonActionPerformed

    private void MoneyTransactionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MoneyTransactionActionPerformed
        Transaction(MoneyAmountTxtfield.getText());
    }//GEN-LAST:event_MoneyTransactionActionPerformed

    private void RenovateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RenovateButtonActionPerformed
        renovate();
    }//GEN-LAST:event_RenovateButtonActionPerformed

    private void SlotsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SlotsButtonActionPerformed
        Slots(SlotsTxtfield.getText());
    }//GEN-LAST:event_SlotsButtonActionPerformed

    private void BackbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackbuttonActionPerformed
        this.dispose();
        try {
            new LoginScreen().setVisible(true);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(UserManagement.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BackbuttonActionPerformed

    private void MoneyAmountTxtfield1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MoneyAmountTxtfield1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MoneyAmountTxtfield1ActionPerformed

    private void MoneyAmountTxtfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MoneyAmountTxtfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MoneyAmountTxtfieldActionPerformed

    private void SubscriptionAmountTxtfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubscriptionAmountTxtfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SubscriptionAmountTxtfieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserManagement().setVisible(true);
            }
        });
    }
    
    private void Transaction (String Amount) {
        Integer AmountIntBalance = null;
        try {
            AmountIntBalance = Integer.parseInt(Amount);
        }
        catch (NumberFormatException e) {
            JOptionPane.showConfirmDialog(null, "You didn't fill in a valid input", "Alert",JOptionPane.PLAIN_MESSAGE);
        }
        if (AmountIntBalance != null) {
            if (AmountIntBalance < 0) {
                JOptionPane.showConfirmDialog(null, "You can't enter a negative number", "Alert",JOptionPane.PLAIN_MESSAGE);
            }
            else {
                EntityManagerFactory emf = Persistence.createEntityManagerFactory("MMORPG_assignmentPU");
                EntityManager em = emf.createEntityManager();

                em.getTransaction().begin();
                Users checkUser = em.find(Users.class, usernameLogIn);
                balanceCurrent = checkUser.getBalance();
                balanceCurrent = balanceCurrent + AmountIntBalance;
                checkUser.setBalance(balanceCurrent);
                MoneyAmountTxtfield1.setText(balanceCurrent.toString());       
                em.getTransaction().commit();
                em.close();
                emf.close(); 
                JOptionPane.showConfirmDialog(null, "You've succesfully added € " + AmountIntBalance + ",- to your balance.", "Succes",JOptionPane.PLAIN_MESSAGE);
            }
        } 
    }
    
    private void Slots (String Amount) {
        Integer AmountIntSlots = null;
        try {
            AmountIntSlots = Integer.parseInt(Amount);
        }
        catch (NumberFormatException e) {
            JOptionPane.showConfirmDialog(null, "You didn't fill in a valid input", "Alert",JOptionPane.PLAIN_MESSAGE);
        }
        if(AmountIntSlots != null) {
            if (AmountIntSlots < 0) {
                JOptionPane.showConfirmDialog(null, "You can't enter a negative number", "Alert",JOptionPane.PLAIN_MESSAGE);
            }
            else if (AmountIntSlots > balanceCurrent) {
                JOptionPane.showConfirmDialog(null, "You don't have enough money to buy that many slots!", "Alert",JOptionPane.PLAIN_MESSAGE);
            }
            else {
                EntityManagerFactory emf = Persistence.createEntityManagerFactory("MMORPG_assignmentPU");
                EntityManager em = emf.createEntityManager();

                em.getTransaction().begin();
                Users checkUser = em.find(Users.class, usernameLogIn);
                slotsCurrent = slotsCurrent + AmountIntSlots;
                checkUser.setCharacterSlots(slotsCurrent);
                SlotsTxtfield1.setText(slotsCurrent.toString());
                balanceCurrent = balanceCurrent - AmountIntSlots;
                checkUser.setBalance(balanceCurrent);
                MoneyAmountTxtfield1.setText(balanceCurrent.toString());       
                em.getTransaction().commit();
                em.close();
                emf.close();
            }
        }          
    }
    
    private void renovate() {
        
    }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Backbutton;
    private javax.swing.JTextField MoneyAmountTxtfield;
    private javax.swing.JTextField MoneyAmountTxtfield1;
    private javax.swing.JButton MoneyTransaction;
    private javax.swing.JRadioButton OneMonthButton;
    private javax.swing.JButton RenovateButton;
    private javax.swing.JButton SlotsButton;
    private javax.swing.JTextField SlotsTxtfield;
    private javax.swing.JTextField SlotsTxtfield1;
    private javax.swing.JTextField SubscriptionAmountTxtfield;
    private javax.swing.JRadioButton YearButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JRadioButton threeMonthsButton;
    private javax.swing.JRadioButton twoMonthsButton;
    // End of variables declaration//GEN-END:variables
}
